### ISSUE TITLE
error 400 undefined

### ISSUE THREAD

**Issue by arist0v** [flatsiedatsie/followers-addon#1]
when i try to configure the addon with the local authorization token, when i hit apply i got an error 400 undefined and can'T get access to things

edit:

i got this log:
2020-07-21 09:31:36.263 INFO   : followers: setting persistence file path failed, will try older method.
2020-07-21 09:31:36.265 INFO   : followers: Current working directory: /home/pi/mozilla-iot/gateway
2020-07-21 09:31:36.267 INFO   : followers: Could not load persistent data (if you just installed the add-on then this is normal)
2020-07-21 09:31:36.270 INFO   : followers: self.persistent_data is now: {'items': []}
2020-07-21 09:31:36.272 INFO   : followers: no user profile data
2020-07-21 09:31:36.275 INFO   : followers: self.manager_proxy = <gateway_addon.addon_manager_proxy.AddonManagerProxy object at 0x75fc9af0>
2020-07-21 09:31:36.277 INFO   : followers: Created new API HANDLER: followers
2020-07-21 09:31:36.280 INFO   : followers: 0.12.0
2020-07-21 09:31:36.282 INFO   : followers: Starting the internal clock
2020-07-21 09:31:36.285 INFO   : followers: Followers shutting down
2020-07-21 09:31:38.275 ERROR  : Failed to restart add-on followers
2020-07-21 09:31:38.283 ERROR  : Error: Checksum failed for file /home/pi/.mozilla-iot/addons/followers/pkg/__pycache__/__init__.cpython-37.pyc in add-on followers
    at find.fileSync.forEach (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:215:1)
    at Array.forEach (<anonymous>)
    at loadManifestJson (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:197:1)
    at Object.loadManifest (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:303:1)
    at AddonManager.loadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:614:1)
    at ./src/controllers/addons_controller.js.AddonsController.put (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/addons_controller.js:114:1)

**Comment by flatsiedatsie** [comment]
Thank you! It has been fixed.

**Comment by arist0v** [comment]
i update the addon, reboot my gateway, and still the same issue:
2020-07-21 14:09:42.059 INFO   : followers: -Authorization token is present in the config data.
2020-07-21 14:09:42.062 INFO   : followers: -Debugging preference was in config: True
2020-07-21 14:09:42.065 INFO   : followers: setting persistence file path failed, will try older method.
2020-07-21 14:09:42.068 INFO   : followers: Current working directory: /home/pi/mozilla-iot/gateway
2020-07-21 14:09:42.070 INFO   : followers: Could not load persistent data (if you just installed the add-on then this is normal)
2020-07-21 14:09:42.073 INFO   : followers: self.persistent_data is now: {'items': []}
2020-07-21 14:09:42.076 INFO   : followers: no user profile data
2020-07-21 14:09:42.079 INFO   : followers: self.manager_proxy = <gateway_addon.addon_manager_proxy.AddonManagerProxy object at 0x75ff3b50>
2020-07-21 14:09:42.082 INFO   : followers: Created new API HANDLER: followers
2020-07-21 14:09:42.089 INFO   : followers: 0.12.0
2020-07-21 14:09:42.092 INFO   : followers: Starting the internal clock
2020-07-21 14:09:42.095 INFO   : followers: Followers shutting down
2020-07-21 14:09:43.342 ERROR  : Failed to restart add-on followers
2020-07-21 14:09:43.348 ERROR  : Error: Checksum failed for file /home/pi/.mozilla-iot/addons/followers/pkg/__pycache__/__init__.cpython-37.pyc in add-on followers
    at find.fileSync.forEach (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:215:1)
    at Array.forEach (<anonymous>)
    at loadManifestJson (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:197:1)
    at Object.loadManifest (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:303:1)
    at AddonManager.loadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:614:1)
    at ./src/controllers/addons_controller.js.AddonsController.put (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/addons_controller.js:114:1)

**Comment by flatsiedatsie** [comment]
Could you try deleting it first? It could be that an update doesn't remove the old file that is causing trouble (don't know).

**Comment by arist0v** [comment]
deleted the add-on
rebooted the add-on
reinstalled the add-on

still same issue

2020-07-22 09:19:20.964 INFO   : Fetching add-on https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/followers-0.1.1.tgz as /tmp/VMNAci/followers.tar.gz
2020-07-22 09:19:21.641 INFO   : Expanding add-on /tmp/VMNAci/followers.tar.gz
2020-07-22 09:19:25.383 INFO   : Loading add-on: followers
2020-07-22 09:19:38.219 INFO   : Unloading API handler followers
2020-07-22 09:19:40.645 INFO   : followers: -Authorization token is present in the config data.
2020-07-22 09:19:40.648 INFO   : followers: -Debugging preference was in config: True
2020-07-22 09:19:40.651 INFO   : followers: setting persistence file path failed, will try older method.
2020-07-22 09:19:40.654 INFO   : followers: Current working directory: /home/pi/mozilla-iot/gateway
2020-07-22 09:19:40.657 INFO   : followers: Could not load persistent data (if you just installed the add-on then this is normal)
2020-07-22 09:19:40.660 INFO   : followers: self.persistent_data is now: {'items': []}
2020-07-22 09:19:40.677 INFO   : followers: no user profile data
2020-07-22 09:19:40.680 INFO   : followers: self.manager_proxy = <gateway_addon.addon_manager_proxy.AddonManagerProxy object at 0x75f82b50>
2020-07-22 09:19:40.682 INFO   : followers: Created new API HANDLER: followers
2020-07-22 09:19:40.685 INFO   : followers: 0.12.0
2020-07-22 09:19:40.687 INFO   : followers: Starting the internal clock
2020-07-22 09:19:40.689 INFO   : followers: Followers shutting down
2020-07-22 09:19:41.786 ERROR  : Failed to restart add-on followers
2020-07-22 09:19:41.793 ERROR  : Error: Checksum failed for file /home/pi/.mozilla-iot/addons/followers/pkg/__pycache__/__init__.cpython-37.pyc in add-on followers
    at find.fileSync.forEach (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:215:1)
    at Array.forEach (<anonymous>)
    at loadManifestJson (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:197:1)
    at Object.loadManifest (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-utils.js:303:1)
    at AddonManager.loadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:614:1)
    at ./src/controllers/addons_controller.js.AddonsController.put (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/addons_controller.js:114:1)

**Comment by flatsiedatsie** [comment]
Hmm. That's odd. It's fixed here.
- What version of the gateway are you using?
- Could you try and delete the file? You can install the Seashell addon and then issue this command with it:
`sudo rm -rf /home/pi/.mozilla-iot/addons/followers/pkg/pycache`
(it removes the cache directory. 'rm' stands for 'remove', and the 'sudo' forces it to happen). 
- Then use the Power Settings addon to reboot the pi.

**Comment by arist0v** [comment]
still got the same issue!

**Comment by flatsiedatsie** [comment]
I just released a potential fix. 

Do you still have the issue on version 0.1.2?

**Comment by arist0v** [comment]
Working thank you!

Le mer. 22 juill. 2020 17 h 18, flatsiedatsie <notifications@github.com> a
écrit :
